# Generated by Django 6.1.1 on 2026-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=10)),
                ("emp_name", models.CharField(max_length=50)),
                ("emp_position", models.CharField(max_length=50)),
            ],
        ),
    ]
