# Generated by Django 6.1.1 on 2026-10-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="employee",
            new_name="Employees",
        ),
    ]
