# Generated by Django 6.1.1 on 2026-09-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stud_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("branch", models.CharField(max_length=50)),
            ],
        ),
    ]
